#!/usr/bin/env python
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep
from selenium.webdriver.common.action_chains import ActionChains

def test_login():
    phone_number = input("Enter your phone number 09:")
    code_meli = input("Enter your meli code:")
    driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
    action = ActionChains(driver=driver)
    driver.get("https://shop.rightel.ir")
    action = ActionChains(driver=driver)
    driver.set_window_size(2000, 694)
    sleep(3)
    el1 = driver.find_element('xpath',"//div[@id='customTab']//a[1]")
    action.click(el1).perform()
    sleep(1)
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight/3);")
    sleep(3)
    el2 = driver.find_element('xpath', "//div[@class='customPane fade show activePan']//div[@class='cardPlan'][1]//button[@class='rightelBtn planBtn'][1]")
    action.click(el2).perform()
    sleep(10)
    # //div[@class='productCard']//img[@title='سیم کارت دائمی آبی']
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight/3);")
    sleep(3)
    el3 = driver.find_element('xpath', "//div[@class='productCard'][1]//div[@class='productCard'][1]//button")
    action.click(el3).perform()
    sleep(3)
    # driver.execute_script("window.scrollTo(0, document.body.scrollHeight/3);")
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight/5);")
    sleep(3)
    click = driver.find_element('xpath',"//div[@id='contentDiv']")
    secure = input("Enter secure Code:")
    sleep(3)
    meli = driver.find_element("xpath", "//div[@class='input-grp']//div[@class='contralContent']//input[@minlength='10']")
    sleep(3)
    meli.send_keys(f"{code_meli}")
    sleep(2)
    phone = driver.find_element("xpath", "//div[@class='input-grp']//div[@class='contralContent']//input[@minlength='9']")
    sleep(2)
    phone.send_keys(f"{phone_number}")
    sleep(4)
    el = driver.find_element('xpath',"//div[@class='form-check form-check-inline m-0']//input[@type='checkbox']")
    sleep(2)
    action.click(el).perform()
    secure_code = driver.find_element("xpath", "//div[@class='input-grp']//div[@class='contralContent mr15']//input[@minlength='6']")
    sleep(6)
    secure_code.send_keys(f"{secure}")
    sleep(5)
    enter = driver.find_element("xpath", "//button[@class='rightelBtn loginButton']//div[@id='contentDiv']")
    action.click(enter).perform()
    sleep(2)
    for i in range(5):
        sms_code = input(f"Enter number {i+1}:")
        sms = driver.find_element("xpath",f"//div[@class='wrapper']//input[{i+1}]")
        sms.send_keys(f"{sms_code}")
        sleep(1)

    enter2 = driver.find_element("xpath", f"//button[@class='rightelBtn loginButton']//div[@id='contentDiv']")
    sleep(1)
    action.click(enter2)
    sleep(5)